stages:
  preprocess_stage:
    cmd: python src/preprocess.py
    deps:
    - data/Raw/online_retail.csv
    - src/preprocess.py
    outs:
    - data/Processed/processed_data.csv
  train_model:
    cmd: python models/train_model.py
    deps:
    - data/Processed/processed_data.csv
    - models/train_model.py
    outs:
    - data/Processed/rfm_clustered.csv
    - models/kmeans_model.pkl
  
  evaluate_model:
    cmd: python metrics/evaluate.py
    deps:
      - data/Processed/rfm_clustered.csv
      - metrics/evaluate.py
    metrics:
      - metrics/cluster_metrics.json
